// src/app/dynamic-map/dynamic-map.component.ts
import {
  Component,
  OnInit,
  OnChanges,
  ChangeDetectionStrategy,
  Input,
  ViewChild,
  ElementRef,
  SimpleChanges
} from '@angular/core'
import setupMap from '../services/setupMap'

import {Map} from 'mapbox-gl'
import {ExposedScope} from '@st-graphics/angular-scrolly'
import {Feature} from '../data'

type FeatureStateSetter = (state: object) => void

@Component({
  selector: 'dynamic-map',
  templateUrl: './dynamic-map.component.html',
  styleUrls: ['./dynamic-map.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DynamicMapComponent implements OnInit, OnChanges {

  @Input() slideIndex: number
  @Input() enter: ExposedScope.enter
  @Input() progress: ExposedScope.progress
  @Input() features: Feature[]

  @ViewChild('base', {static: true}) mapContainer: ElementRef

  map: Map = null
  featureStateSetters: FeatureStateSetter[] = null

  constructor () {}

  get currentFeature () {
    return this.features[this.slideIndex]
  }

  ngOnInit () {
    setupMap(this.mapContainer.nativeElement, map => {
      const mapFeatures = map.querySourceFeatures('osmbuildings', {sourceLayer: 'building'})
      this.map = map
      this.featureStateSetters = this.features.map(row => {
        const filtered = mapFeatures.filter(row.filter)
        return state => filtered.forEach(f => {
          map.setFeatureState({
            source: 'osmbuildings',
            sourceLayer: 'building',
            id: f.id
          }, state)
        })
      })
    })
  }

  ngOnChanges (changes: SimpleChanges) {
    if (this.featureStateSetters && changes.slideIndex) {
      this.featureStateSetters.forEach((setter, i) => {
        const highlighted = i === changes.slideIndex.currentValue
        setter({highlighted})
      })
    }
      
    if (this.featureStateSetters && changes.enter) {
      const enter = changes.enter.currentValue
      this.featureStateSetters.forEach((setter, i) => {
        const factor = Math.max(enter(i, 300, 0), 1 - enter(i, 30, -300))
        setter({factor})
      })
    }

    if (this.featureStateSetters && changes.progress) {
      const t = changes.progress.currentValue.at(this.features.length)(true) || 0
      const b = (1 - t) * 190 + t * 60
      this.map.setBearing(b)
    }
  }
}

<div class="dynamic-map">
  <div class="map-container" #base></div>
  <h1 class="rank">排名第 {{currentFeature.rank}}</h1>
</div>

// src/components/DynamicMap.jsx
import React, {useState, useEffect, useRef} from 'react'
import './DynamicMap.scss'

import setupMap from '../services/setupMap'

function DynamicMap (props) {
  const $base = useRef(null)
  const mapRef = useRef(null)
  const [featureStateSetters, setFeatureStateSetters] = useState(null)
  
  const {features, slideIndex, enter, progress} = props
  const currentFeature = features[slideIndex]
  
  useEffect(() => {
    mapRef.current = setupMap($base.current, map => {
      const mapFeatures = map.querySourceFeatures('osmbuildings', {sourceLayer: 'building'})
      const featureStateSetters = features.map(row => {
        const filtered = mapFeatures.filter(row.filter)
        return state => filtered.forEach(f => {
          map.setFeatureState({
            source: 'osmbuildings',
            sourceLayer: 'building',
            id: f.id
          }, state)
        })
      })
      setFeatureStateSetters(featureStateSetters)
    })
  }, [features])

  useEffect(() => {
    if (!featureStateSetters) return
    featureStateSetters.forEach((setter, i) => {
      const highlighted = i === slideIndex
      setter({highlighted})
    })
  }, [featureStateSetters, slideIndex])

  useEffect(() => {
    if (!featureStateSetters) return
    featureStateSetters.forEach((setter, i) => {
      const factor = Math.max(enter(i, 300, 0), 1 - enter(i, 30, -300))
      setter({factor})
    })
  }, [featureStateSetters, enter])

  useEffect(() => {
    if (!featureStateSetters) return
    const map = mapRef.current
    const t = progress.at(features.length)(true)
    const b = (1 - t) * 190 + t * 60
    map.setBearing(b)
  }, [featureStateSetters, progress, features.length])

  return (
    <div className="dynamic-map">
      <div className="map-container" ref={$base}></div>
      <h1 className="rank">排名第 {currentFeature.rank}</h1>
    </div>
  )
}

export default DynamicMap
