// src/components/MyHeader.vue
<template functional>
  <header class="my-header" :key="data.key">
    <h1>Scrollytelling Demo</h1>
    <h1>滚动叙事 示范</h1>
  </header>
</template>

<style lang="scss">
.my-header {
  height: 100vh;
  background-color: #333;
  display: flex;
  flex-direction: column;
  justify-content: center;

  h1 {
    font-size: 72px;
    color: white;
  }
}
</style>

// src/components/MyHeader.svelte
<header class="my-header" :key="data.key">
  <h1>Scrollytelling Demo</h1>
  <h1>滚动叙事 示范</h1>
</header>

<style lang="scss">
.my-header {
  height: 100vh;
  background-color: #333;
  display: flex;
  flex-direction: column;
  justify-content: center;

  h1 {
    font-size: 72px;
    color: white;
  }
}
</style>
