// src/app/my-story/my-story.component.ts
import {Component, ViewEncapsulation} from '@angular/core'
import {features} from '../data'

import {clamp} from '@st-graphics/angular-scrolly'

@Component({
  selector: 'my-story',
  templateUrl: './my-story.component.html',
  styleUrls: ['./my-story.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class MyStoryComponent {
  features = features.reverse()
  clamp = clamp
}

<div class="my-story">
  <st-scrolly
    [backgroundTemplate]="background"
    [slidesTemplate]="slides"
    [triggerOffset]="-300">
  </st-scrolly>
  
  <ng-template #background let-slideIndex="slideIndex" let-enter="enter" let-progress="progress">
    <dynamic-map
      [slideIndex]="clamp(slideIndex, 0, features.length - 1)"
      [enter]="enter"
      [progress]="progress"
      [features]="features">
    </dynamic-map>
  </ng-template>

  <ng-template #slides let-enter="enter">
    <div class="slide" *ngFor="let f of features; index as i">
      <p class="card" [ngStyle]="{opacity: enter(i, 400, -100)}">
        {{f.name_chi}} ({{f.year}})<br>{{f.height}} m
      </p>
    </div>
    <div class="final slide"></div>
  </ng-template>
</div>

// src/components/MyStory.jsx
import React from 'react'
import '@st-graphics/react-scrolly/dist/bundle.css'
import './MyStory.scss'

import StScrolly, {clamp} from '@st-graphics/react-scrolly'
import DynamicMap from './DynamicMap'

import * as data from '../data'

const features = data.features.reverse()

export default function MyStory () {
  const renderBackground = data => (
    <DynamicMap
      slideIndex={clamp(data.slideIndex, 0, features.length - 1)}
      enter={data.enter}
      progress={data.progress}
      features={features} />
  )

  const children = data => features.map((slide, i) => (
    <div className="slide" key={slide.rank} style={getStyle(data.enter, i)}>
      <p className="card">{slide.name_chi} ({slide.year})<br />{slide.height} m</p>
    </div>
  )).concat(<div className="final slide" key="final"></div>)

  return (
    <StScrolly className="my-story"
      triggerOffset={-300}
      renderBackground={renderBackground}>
      {children}
    </StScrolly>
  )
}

function getStyle (enter, i) {
  return {
    opacity: enter(i, 400) || 0
  }
}
