// src/App.vue
<template>
  <div id="app">
    <my-header></my-header>
    <my-story></my-story>
    <my-footer></my-footer>
  </div>
</template>

<script>
import MyHeader from './components/MyHeader'
import MyFooter from './components/MyFooter'
import MyStory from './components/MyStory.vue'

export default {
  name: 'app',
  components: {
    MyHeader,
    MyStory,
    MyFooter
  }
}
</script>

<style lang="scss">
html,
body {
  margin: 0;
  padding: 0;
}

#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
</style>

// src/App.svelte
<div id="app">
	<MyHeader/>
	<MyStory/>
	<MyFooter/>
</div>

<script>
import MyHeader from './components/MyHeader.svelte'
import MyFooter from './components/MyFooter.svelte'
import MyStory from './components/MyStory.svelte'
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
</style>
